### ISSUE TITLE
PHP download page for 8.2.8 is no longer available

### ISSUE THREAD

**Issue by capegreg** [php/web-php#798]
I apologize if this is not the right place to ask this question, but I followed the recommended contacts at PHP "Help" by sending an email to php-webmaster@lists.php.net, but that address was rejected as well as doc-bugs@lists.php.net. Guessing this page is not getting updates, so I’m asking my question here.

The Windows PHP zip release on PHP download page for 8.2.8 is no longer available. Clicking the Windows download link for 8.2.8 takes you to the latest version of 8.2.9.

https://windows.php.net/downloads/releases/php-8.2.9-nts-Win32-vs16-x64.zip

https://windows.php.net/download#php-8.2

The latest version as of August 4, 2023 is “Current Stable PHP 8.2.8” but Windows version shows PHP 8.2.9 as of 2023-Aug-01 13:21:56

**Comment by saundefined** [comment]
Hi, thanks for the issue.

Sorry this happened, this is due to the fact that PHP 8.2.9 has not been announced yet as the Windows builds were built on the old tag and should be rebuilt, but they have already replaced the 8.2.8 files.

I might suggest waiting for a new build for Windows 8.2.9 and the official announcement of the new release.

**Comment by capegreg** [comment]
Ok. Much appreciated.
