### ISSUE TITLE
Troyan? / Download / Windows / ZIP / VS16 x64 Non Thread Safe

### ISSUE THREAD

**Issue by EarthDweller** [php/web-php#905]
[windows.php.net](https://windows.php.net/download#php-8.3)

VS16 x64 Non Thread Safe (2023-Dec-20 14:25:40)
[Zip](https://windows.php.net/downloads/releases/php-8.3.1-nts-Win32-vs16-x64.zip) [30.64MB]

Kaspersky messaged, that that file is troyan:
php-8.3.1.tar\php-8.3.1\ext\phar\tests\bug81726.gz

Actually I don't understand where it is

**Comment by Apetree100122** [comment]
````php
win
dows.php.net
VS1
6 
x64 Non Thre
ad S
afe (
20
23-Dec-
20 1
4:25:4
0)
Zip [3
0.64MB]
Kaspersk
y me
ssage
d, that t
hat f
ile is troy
an:
php-8
.3.1.tar\ph
p-8.3.1
\ext
\phar\
tests\bug
8172
6.gz
````

**Comment by saundefined** [comment]
Hi,

I just checked with the latest Kaspersky databases,
I can't find any threats in this archive.

Can you run it again?
Are threats found in later versions of PHP, or does this only apply to 8.3.1?

**Comment by cmb69** [comment]
The mentioned file is part of a test for a [fixed security bug](https://bugs.php.net/bug.php?id=81726), so it is not too unlikely that it may be flagged as malware. However, this is neither Windows specific, nor related to this repository, since it is https://github.com/php/php-src/blob/master/ext/phar/tests/bug81726.gz. I don't think, though, that any action is needed – except, maybe to explicitly tell users that the test suite may contain files which may be flagged as malware (and *might* cause other software to malfunction, if the respective files are used with that software).
