### ISSUE TITLE
heap.space seems unavailable

### ISSUE THREAD

**Issue by kczx3** [php/web-php#918]
Just an FYI that it seems heap.space is, at least currently, unavailable.  lxr.php.net still is too.
 
https://github.com/php/web-php/blob/533d58a54e36f3619628c3fca4fbdef7785f551e/get-involved.php#L57

**Comment by topdev658** [comment]
If heap.space and lxr.php.net are currently unavailable, it could be due to temporary server issues, maintenance, or other reasons. The availability of external websites can vary, and intermittent outages are not uncommon.

To check for updates on the status of these services, you may want to visit their official websites or follow any announcements they may have on social media or other channels. Additionally, you can try accessing the websites at a later time.

If you have any specific questions or if there's anything else I can assist you with, feel free to let me know!

**Comment by tiffany-taylor** [comment]
@kczx3 can you confirm that it still doesn't work for you? It is hosted by a volunteer, so there may days where maintenance occurs, that is, it won't have 100% uptime. With that said, I'm able to access it fine.
