### ISSUE TITLE
$mysqli->change_user returns Access denied NO password

### ISSUE THREAD

**Issue by greatgraphicdesign** [php/web-php#931]
PHP 8.2.14
MySQL 5.7.23-23 - Percona Server (GPL), Release 23, Revision 500fcf5
This is on a shared webhost with CPanel

I'm importing this test script on page load...
```
$conn = new mysqli("localhost", "<username1>", "<password1>", "<dbname>");
$conn->change_user("<username2>", "<password2>", "<dbname>");
```
If I remove line 2, there is no error. This is true with either set of credentials, so I know for a fact that I'm passing the correct credentials and that they work. Since I'm passing the strings directly, I can't see how a no password error could be possible.
```
[24-Jan-2024 21:11:56 America/Boise] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user '<username2>'@'localhost' (using password: NO) in /home1/user/public_html/site/folder/script.php:69
Stack trace:
#0 /home1/user/public_html/site/folder/script.php(69): mysqli->change_user('<username2>', Object(SensitiveParameterValue), '<dbname>')
#1 /home1/user/public_html/site/index.php(47): require_once('/home1/user...')
#2 {main}
  thrown in /home1/user/public_html/site/folder/script.php on line 69
```

**Comment by kamil-tekiela** [comment]
Thank you for this bug report. However, it's highly unlikely that this is a problem with PHP. At least there is no indication of this being true. Given that you are running Percona 5.7 which is built on top of MySQL 5.7, you are most likely running into this MySQL bug https://bugs.mysql.com/bug.php?id=102266. This was fixed in 5.7.35. Please upgrade either to Percona 8 or Percona 5.7.35 or Percona 5.7.44 which was the last version ever to be released for the EOL 5.7 branch. It's highly recommended that you do not run outdated software. 

Alternatively, you can just not use `change_user` at all. You can replace it with `$mysqli->connect('localhost', "<username2>", "<password2>", "<dbname>");` which has the only inconvenience of having to provide the hostname parameter again, or you can just create a new mysqli connection altogether. The end result should be the same or possibly even better (tbh I am not sure what the selling point of `change_user` is or its intended purpose).

I will mark this issue as awaiting feedback. If we do not hear back from you soon, we will assume that the upgrade to a more recent Percona version resolved the issue.

**Comment by alek-womple** [comment]
Thank you very much! I'll need a couple of days to explore the solution and respond. I will do so ASAP.

**Comment by greatgraphicdesign** [comment]
Thank you very much! I'll need a couple of days to explore the solution and respond. I will do so ASAP.

**Comment by greatgraphicdesign** [comment]
My client's webhost, BlueHost, explained they cannot update MySQL upon request since this is a shared hosting account. I'm afraid my client is stuck with MySQL 5.7.23 until the host rolls out an update on their own schedule. That's too bad.

On the bright side, your `$conn->connect` suggestion is working perfectly. Thank you for the workaround! I'm sorry I am unable to verify the fix, given the hosting situation.

**Comment by Girgias** [comment]
Closing as this is not an issue with PHP.
